// <auto-generated />
using System;
using Guadalupe.Conexao.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guadalupe.Conexao.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ConexaoContext))]
    [Migration("20220406194156_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Guadalupe.Conexao.Api.Domain.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<Guid>("IdPostedBy")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id_posted_by");

                    b.Property<string>("Image")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("Modification")
                        .HasColumnType("datetime")
                        .HasColumnName("modification_date");

                    b.Property<DateTime>("Registration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Removal")
                        .HasColumnType("datetime")
                        .HasColumnName("removal_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("IdPostedBy");

                    b.ToTable("notice", (string)null);
                });

            modelBuilder.Entity("Guadalupe.Conexao.Api.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Modification")
                        .HasColumnType("datetime")
                        .HasColumnName("modification_date");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("ProfileImage")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("profile_image");

                    b.Property<DateTime>("Registration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Removal")
                        .HasColumnType("datetime")
                        .HasColumnName("removal_date");

                    b.HasKey("Id");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Guadalupe.Conexao.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id");

                    b.Property<string>("CodeAccess")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code_access");

                    b.Property<string>("FCMToken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("fcm_token");

                    b.Property<Guid>("IdPerson")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("id_person");

                    b.Property<DateTime?>("Modification")
                        .HasColumnType("datetime")
                        .HasColumnName("modification_date");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("Registration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Removal")
                        .HasColumnType("datetime")
                        .HasColumnName("removal_date");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Guadalupe.Conexao.Api.Domain.Notice", b =>
                {
                    b.HasOne("Guadalupe.Conexao.Api.Domain.Person", "PostedBy")
                        .WithMany()
                        .HasForeignKey("IdPostedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostedBy");
                });

            modelBuilder.Entity("Guadalupe.Conexao.Api.Domain.User", b =>
                {
                    b.HasOne("Guadalupe.Conexao.Api.Domain.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Guadalupe.Conexao.Api.Domain.User", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
